# pigsty singleton-meta environment (2C8G)

Specs = [
  { "name" => "meta"          , "ip" => "192.168.1.193"   , "cpu" => "2"    , "mem" => "8192"    , "image" =>  "generic/rocky9"   },
]

Vagrant.configure("2") do |config|

    config.vm.box_check_update = false
    
    config.vm.provision "shell" do |s|
      s.inline = <<-SHELL
        sudo dnf update -y
        sudo dnf install -y ansible python3.11-jmespath python3-cryptography
        echo "strict=0" | sudo tee -a /etc/yum.conf /etc/dnf/dnf.conf
        chown -R vagrant:vagrant /home/vagrant
        exit 0
      SHELL
    end

    Specs.each_with_index do |spec, index|
        config.vm.define spec["name"] do |node|
            node.vm.box = spec["image"]
            node.vm.network "public_network",
              :ip => $vm_public_ip,
              :dev => "br0",
              :mode => "bridge",
              :type => "bridge",
              :mac => "5A74CA285801"
                      node.vm.hostname = spec["name"]
            node.vm.provider "libvirt" do |v|
                v.cpus   =  spec["cpu"]
                v.memory =  spec["mem"]

                # provision an additional disk for minio nodes
                if spec["name"].start_with?("minio")
                    v.storage :file, :size => '128G', :device => 'vdb'
                    node.vm.provision "shell" do |s|
                      s.inline = <<-SHELL
                        mkdir -p /data; mkfs.xfs /dev/vdb;
                        mount -o noatime -o nodiratime -t xfs /dev/vdb /data;
                        echo "/dev/vdb /data xfs defaults,noatime,nodiratime 0 0" >> /etc/fstab;
                      SHELL
                    end
                end
            end
        end
    end
end
