
# This is the Vagrantfile template for libvirt (KVM) which require vagrant-libvirt plugin to work
# check https://vagrant-libvirt.github.io/vagrant-libvirt/ for details

# read ssh key from current user's ~/.ssh
ssh_prv_key = File.read(File.join(ENV['HOME'], '.ssh', 'id_rsa'))
ssh_pub_key = File.readlines(File.join(ENV['HOME'], '.ssh', 'id_rsa.pub')).first.strip

vm_public_ip = "192.168.1.211"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box_check_update = false
  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
      if grep -sq "#{ssh_pub_key}" /home/vagrant/.ssh/authorized_keys; then
        echo "SSH keys already provisioned." ; exit 0;
      fi
      echo "SSH key provisioning."
      sshd=/home/vagrant/.ssh
      mkdir -p ${sshd}; touch ${sshd}/{authorized_keys,config}
      echo #{ssh_pub_key}   >> ${sshd}/authorized_keys
      echo #{ssh_pub_key}   >  ${sshd}/id_rsa.pub      ; chmod 644 ${sshd}/id_rsa.pub
      echo "#{ssh_prv_key}" >  ${sshd}/id_rsa          ; chmod 600 ${sshd}/id_rsa
      if ! grep -q "StrictHostKeyChecking" ${sshd}/config; then
          echo 'StrictHostKeyChecking=no' >> ${sshd}/config
      fi
      chown -R vagrant:vagrant /home/vagrant


      sudo dnf install -y ansible python3.11-jmespath
      curl -fsSL https://get.pigsty.cc/latest | bash

      cd ~/pigsty   # get pigsty source and entering dir
      ./bootstrap   # download bootstrap pkgs & ansible [optional]
      ./configure   # pre-check and config templating   [optional] 
      ./install.yml # install pigsty according to pigsty.yml
    SHELL
  end

  config.vm.define "pigsty-1" do |node|
    node.vm.box = "generic/rocky9"
    node.vm.network "public_network",
    :ip => $vm_public_ip,
    :dev => "br0",
    :mode => "bridge",
    :type => "bridge",
    :mac => "5A74CA285801"
    node.vm.hostname = "pigsty"
    node.vm.provider "libvirt" do |v|
        v.cpus   =  2
        v.memory =  8192
    end
  end

  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
      sudo dnf install -y ansible python3.11-jmespath
      curl -fsSL https://get.pigsty.cc/latest | bash

      cd ~/pigsty   # get pigsty source and entering dir
      ./bootstrap   # download bootstrap pkgs & ansible [optional]
    SHELL
  end
  
  config.vm.provision "file", source: "pigsty.yml", destination: "~/pigsty/pigsty.yml"

  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
      cd ~/pigsty   # get pigsty source and entering dir
      ./install.yml
    SHELL
  end
  

end