Vagrant.require_version '>= 2.0.4'

$num_node = 2 

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y nfs-common
  SHELL

  (1..$num_node).each do |i|
    config.vm.define "k8s-#{i}" do |node|
      node.vm.provider "libvirt" do |v|
        v.memory = 8192
        v.cpus = 2
      end
      node.vm.network "public_network",
        :ip => "192.168.1.19#{i}",
        :dev => "br0",
        :mode => "bridge",
        :type => "bridge"

      node.vm.network "private_network", ip: "192.168.10.6#{i}"
    end
  end
end
